### ISSUE TITLE
Changes to the hello component to run locally

### ISSUE THREAD

**Issue by anishcr** [rawkode/advent-of-spin#1]
Hi,
  Your code is very helpful, especially i could not figure out how to get the base url in Hello component to call the lowercase outbound http.
  
  I had to add and make couple of changes to the code to get it running locally http (instead of https) and with a port number. When we deploy to fermyon cloud, your code works perfectly.
  
  ```
     let host = uri.host().unwrap();
     let scheme = uri.scheme().unwrap();
     let port = uri.port_u16();
 
     let domain = match port {
         Some(port_no) => format!("{scheme}://{host}:{port_no}"),
         None => format!("{scheme}://{host}"),
     };  
```
and changed the uri to the following.

```
.uri(format!("{}/lowercase", domain))
```

**Comment by rawkode** [comment]
Yeah. I filed a bug report with Fermyon about the protocol being reported incorrectly on spin-full-url. Hoping it is fixed quickly 😀

**Comment by anishcr** [comment]
Thank you.

When i uploaded to Fermyon, the above code was not working.

The scheme was returning http and hence the http post was not working.

So changed the code to

```
     let host = uri.host().unwrap();
     let mut scheme = uri.scheme().unwrap().as_str();
     let port = uri.port_u16();
 
     if host.contains(".fermyon.") {
         scheme = "https";
     }   
 
     let domain = match port {
         Some(port_no) => format!("{scheme}://{host}:{port_no}"),
         None => format!("{scheme}://{host}"),
     };  
```

Just FYI.
